name: My First Workflow

on:
    push:
        branches:
            - main


jobs:
    hello:
        runs-on: ubunto-latest

        steps:
            - name Say Hello
            run: echo "Hello From Github Actions) "